# src/config.py

SIMULATION_HOURS = 24
TIME_STEP_HOURS = 1


# Ahmedabad case study location
CITY = "Ahmedabad, Gujarat, India"
LATITUDE = 23.033863
LONGITUDE = 72.585022
TIMEZONE = "Asia/Kolkata"

# PV system assumptions
PV_SIZE_KW = 5.0
PV_TILT_DEGREES = 23
PV_AZIMUTH_DEGREES = 180
PV_DERATE_FACTOR = 0.85

# Battery system
BATTERY_CAPACITY_KWH = 10.0
BATTERY_MAX_CHARGE_KW = 5.0
BATTERY_MAX_DISCHARGE_KW = 5.0
BATTERY_EFFICIENCY = 0.95

SOC_MIN = 0.20
SOC_MAX = 0.90
SOC_INITIAL = 0.50

# EV charging
EV_CHARGER_POWER_KW = 7.2
EV_REQUIRED_ENERGY_KWH = 18.0
EV_ARRIVAL_HOUR = 18
EV_DEPARTURE_HOUR = 8

# Electricity tariff
GRID_IMPORT_PRICE = 8.0   # Rs/kWh
GRID_EXPORT_PRICE = 3.0   # Rs/kWh

# Long-term simulation
DAYS_PER_YEAR = 365
HOURS_PER_DAY = 24
FULL_YEAR_HOURS = DAYS_PER_YEAR * HOURS_PER_DAY